### ISSUE TITLE
ImportCSV fails with cannot import name 'Units' from 'hydra_base.lib.units'

### ISSUE THREAD

**Issue by robhoney** [UMWRG/csv-app#2]
Trying to run importcsv, gives the following error:

ImportError: cannot import name 'Units' from 'hydra_base.lib.units'

'Units' does not seem to exist in that file, hence the error. Please see rest of trace below:

> (base) C:\HydraSrc\csv-app\ImportCSV>python importcsv.py -h
> 18332 2019-11-05 15:56:09,018 - INFO - Registering data type "SCALAR".
> 18332 2019-11-05 15:56:09,018 - INFO - Registering data type "ARRAY".
> 18332 2019-11-05 15:56:09,019 - INFO - Registering data type "DESCRIPTOR".
> 18332 2019-11-05 15:56:09,020 - INFO - Registering data type "DATAFRAME".
> 18332 2019-11-05 15:56:09,020 - INFO - Registering data type "TIMESERIES".
> Traceback (most recent call last):
>   File "importcsv.py", line 28, in <module>
>     from hydra_client.plugin import JsonConnection
>   File "C:\Users\honeywillrs\AppData\Local\Continuum\anaconda3\lib\site-packages\hydra_client\__init__.py", line 23, in <module>
>     from .plugin import *
>   File "C:\Users\honeywillrs\AppData\Local\Continuum\anaconda3\lib\site-packages\hydra_client\plugin.py", line 27, in <module>
>     from hydra_base.lib.units import Units
> ImportError: cannot import name 'Units' from 'hydra_base.lib.units' (C:\HydraSrc\csv-app\ImportCSV\hydra_base\lib\units.py)

**Comment by knoxsp** [comment]
I have released a new version of hydra-client-python so that may fix the issue.
The issue is not the lack of a file called units, rather there is no class 'Units' any more. We've gone back to a more consistent flat structure with no 'Units' class because the units and dimensions are now stored in the database, in a more consistenty way with other stuff.
