### ISSUE TITLE
Code needs porting to Python 3

### ISSUE THREAD

**Issue by robhoney** [UMWRG/csv-app#3]
I noticed in ImportCSV.py that the exception handling seems to be using the Python 2 exception handling notation:

> except Exception, e:

which needs changing to 

> except Exception as e:

for Python 3, which I presume is what it should be to be in line with the rest of the platform?

**Comment by knoxsp** [comment]
I have ported this to python 3 now. THere may be 1 or 2 areas outstanding, but the basics now work
